language: java
install: cp pom.xml ./java && cd java && mvn package -DskipTests && cd -
script: bash ./build.sh
deploy:
  provider: releases
  api_key:
    secure: Hi08cgOjP5OfRn6x7+7ULNl48o7XavxRUM0EIzvS713KVkE+udQMV1Lm+GGFoFa7ZS/ZAGEKuKTC2c/CT4VNnGVPk0GeqjGuzPfNhbUwnhIatn46DIuZG6B7Ala1IyZtQ98ht4tlmrTs9H/Q7E50w2o7QOe2YBy37YthF80OptHU734OnYjRj/Oc81XzuI2yZopQslXVPt23hFEOJW6ogarbEXCV3DmCB3fpokLgqCbbr66yUXcPLJ+TDEt/MbBjAqR2OxHvns96LgVlOc+4W5fSoGEPh9jXfBot4zVqgX1N8fKnbn7eBQghlp7ICjFnql9Oc7UW+WrP33voQd4lHqJ94rL8F68TfYWf6ga0tS8XtsBBfHxhPksd7IC+xPSUsHIvcGgcFamANd7810sisde98um0+tEb2Q6Ic/C8ppfKIcBQaV2zayya8GoNNGOePpQqW8E219UUY8Omy9jIFFi9yF3Lohbns9Em9a5hB2J/IazveG4uH3TbXvdnol9tiGw4dTDmGTzJED8DZD54zgvv13dHdrdMHN3xPYQg9Q+/qN4YabQCcIZlnt+1Lt+1dLGVQ5uf/wfEkzfXf+ZOyNVYNtaP7pQGI3FUV9P14Q8GWWrjLXslRrwbas/GO1WsJ4/lIuL35DupHYglGntQoyb/gIAjBNCDk/FM2xcrhBk=
  file_glob: true
  file: ./target/RODPS*.tar.gz
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
